name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - run: |
        sudo apt install -y make

    - name: Build
      run: make -j B=1

    - name: Test
      run: make -j test

    - name: Benchmark
      run: |
        ./test/h2b.py test/bins/fib40_slow.hex fib40_slow.bin
        ./rvm fib40_slow.bin
        ./rvm test/large-bin
