name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - run: |
        sudo apt install -y make

    - name: Build
      run: make -j test

    - name: Benchmark
      run: |
        set +e
        echo "cnt_1bill"
        ./test/test ./test/cnt_1bill
        echo "nops"
        ./test/test ./test/nops
        exit 0
